version: "3"
services:
  api:
    tty: true
    stdin_open: true
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8005:8005'
    image: fastapi-template:v1.0
    container_name: fastapi
    volumes:
      - ./api/src:/app
    env_file:
      - ./api/dev.env
  db:
    image: mysql:5.7
    container_name: db
    platform: linux/x86_64  # M1 Macの場合必要
    #environmentは本来はenvファイルで管理すること
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3308:3308
    command: --port 3308
    tty: true


