version: "3"
services:
  api:
    tty: true
    stdin_open: true
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - '8006:8006'
    image: fastapi-template-prod:v1.0
    container_name: fastapi
    env_file:
      - ./api/prod.env


